theme: jekyll-theme-tactile
title: lyteforce dot ca
description: Just a singular place to keep track of the somethings I do while I continue to learn how to do the somethings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap